// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_H5Lb3Uq_CicuPOWh_4pIXTKw3eMLT8',
    appId: '1:746368852742:web:04220ed73c4734b8403487',
    messagingSenderId: '746368852742',
    projectId: 'atelier4-p-haimoudi-iir5g1',
    authDomain: 'atelier4-p-haimoudi-iir5g1.firebaseapp.com',
    storageBucket: 'atelier4-p-haimoudi-iir5g1.firebasestorage.app',
    measurementId: 'G-4XPQ2Q4V09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfdOrDdr8AsqKTJX0-CvloF0pwUGI_Cb4',
    appId: '1:746368852742:android:976f56f653c18223403487',
    messagingSenderId: '746368852742',
    projectId: 'atelier4-p-haimoudi-iir5g1',
    storageBucket: 'atelier4-p-haimoudi-iir5g1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LUQ0bvsdWUqheiumLkheAt1ejDOJwvk',
    appId: '1:746368852742:ios:58da7222698d1af7403487',
    messagingSenderId: '746368852742',
    projectId: 'atelier4-p-haimoudi-iir5g1',
    storageBucket: 'atelier4-p-haimoudi-iir5g1.firebasestorage.app',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3LUQ0bvsdWUqheiumLkheAt1ejDOJwvk',
    appId: '1:746368852742:ios:58da7222698d1af7403487',
    messagingSenderId: '746368852742',
    projectId: 'atelier4-p-haimoudi-iir5g1',
    storageBucket: 'atelier4-p-haimoudi-iir5g1.firebasestorage.app',
    iosBundleId: 'com.example.productapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH_H5Lb3Uq_CicuPOWh_4pIXTKw3eMLT8',
    appId: '1:746368852742:web:90a7b7f5c6668a9e403487',
    messagingSenderId: '746368852742',
    projectId: 'atelier4-p-haimoudi-iir5g1',
    authDomain: 'atelier4-p-haimoudi-iir5g1.firebaseapp.com',
    storageBucket: 'atelier4-p-haimoudi-iir5g1.firebasestorage.app',
    measurementId: 'G-WCS6WVBCGP',
  );
}
